/// <summary>
/// This codeunit is responsible for integrating with the KNH Product API. It contains methods to send HTTP requests (GET, POST, PUT, PATCH, DELETE) to the KNH API endpoints, utilizing the payloads generated by the "KNH Product Payload" codeunit and processing the responses with the "KNH Product Response" codeunit. The integration includes error handling to ensure that any issues with the API calls are properly managed and communicated to the user.
/// </summary>
namespace KNHAPIConsumption;
using System.RestClient;
using System.Text;

codeunit 53704 "KNH Product Integration"
{
    var
        KNHProductPayload: Codeunit "KNH Product Payload";
        KNHProductResponse: Codeunit "KNH Product Response";
        KNHRestAPIMgmt: Codeunit "KNH Rest Api Mgmt.";
        ResponseStatus: Boolean;
        HttpMethod: Enum "Http Method";
        HttpClient: HttpClient;
        ResponseMsg: HttpResponseMessage;
        Password, Username : Text;

    internal procedure GetRecord(URLToAccess: Text)
    begin
        this.CheckUrlAndReset(URLToAccess);
        this.ResponseMsg := this.KNHRestApiMgmt.MakeRequest(URLToAccess, this.GetHttpRequestMessage(this.KNHProductPayload.GetProductPayload()), this.HttpMethod::GET);
        this.KNHProductResponse.GetResponse(this.ResponseMsg);
    end;

    internal procedure PostRecord(URLToAccess: Text)
    begin
        this.CheckUrlAndReset(URLToAccess);
        this.ResponseMsg := this.KNHRestApiMgmt.MakeContentRequest(URLToAccess, this.HttpClient, this.GetContentwithHeader(this.KNHProductPayload.PostProductPayload()), this.HttpMethod::POST);
        this.KNHProductResponse.PostResponse(this.ResponseMsg);
    end;

    internal procedure PutRecord(URLToAccess: Text)
    begin
        this.CheckUrlAndReset(URLToAccess);
        this.ResponseMsg := this.KNHRestApiMgmt.MakeContentRequest(URLToAccess, this.HttpClient, this.GetContentwithHeader(this.KNHProductPayload.PutProductPayload()), this.HttpMethod::PUT);
        this.KNHProductResponse.PutResponse(this.ResponseMsg);
    end;

    internal procedure PatchRecord(URLToAccess: Text)
    begin
        this.CheckUrlAndReset(URLToAccess);
        this.ResponseMsg := this.KNHRestApiMgmt.MakeContentRequest(URLToAccess, this.HttpClient, this.GetContentwithHeader(this.KNHProductPayload.PatchProductPayload()), this.HttpMethod::PATCH);
        this.KNHProductResponse.PatchResponse(this.ResponseMsg);
    end;

    internal procedure DeleteRecord(URLToAccess: Text)
    begin
        this.CheckUrlAndReset(URLToAccess);
        this.ResponseMsg := this.KNHRestApiMgmt.MakeContentRequest(URLToAccess, this.HttpClient, this.GetContentwithHeader(this.KNHProductPayload.DeleteProductPayload()), this.HttpMethod::DELETE);
        this.KNHProductResponse.DeleteResponse(this.ResponseMsg);
    end;

    local procedure CheckUrlAndReset(URLToAccess: Text)
    begin
        if URLToAccess = '' then
            Error('URL cannot be empty');

        if StrPos(URLToAccess, '%1') > 0 then
            Error('Execute URL cannot have %1');

        Clear(this.ResponseMsg);
        Clear(this.HttpMethod);
        Clear(this.ResponseStatus);
    end;

    procedure GetContentwithHeader(Payload: Text) Content: HttpContent
    var
        contentHeaders: HttpHeaders;
    begin
        Clear(this.HttpClient);
        if Payload <> '' then
            Content.WriteFrom(Payload);

        Content.GetHeaders(contentHeaders);
        contentHeaders.Clear();
        contentHeaders.Add('Content-Type', 'application/json');
    end;

    local procedure GetHttpRequestMessage(payload: Text) RequestMessage: HttpRequestMessage
    var
        HttpContent: HttpContent;
        ContentHeader, RequestHeader : HttpHeaders;
    begin
        RequestMessage.GetHeaders(RequestHeader);
        RequestHeader.Add('Authorization', this.GetAuthroizationHeader());
        RequestHeader.Add('If-Match', '*');

        HttpContent.WriteFrom(payload);
        HttpContent.GetHeaders(ContentHeader);
        ContentHeader.Remove('Content-Type');
        ContentHeader.Add('Content-Type', 'application/json');

        RequestMessage.Content(HttpContent);
    end;

    local procedure GetAuthroizationHeader() AuthString: Text
    var
        Base64Convert: Codeunit "Base64 Convert";
        AuthStringLbl: Label 'Basic %1', Comment = '%1 = Username';
    begin
        AuthString := StrSubstNo('%1:%2', 'keithhow@metronet.co.uk', 'ChelseaRoyalBlue@9238');
        AuthString := Base64Convert.ToBase64(AuthString);
        AuthString := StrSubstNo(AuthStringLbl, AuthString);
    end;
}